var backbone = require("backbone");
var HeaderView = require("./header_view");
var ContentHeaderView = require("./content_header");
var FooterView = require("./footer_view");

var data = {   'pan-especiales': {   'headerText': 'Especiales',
                          'photo': '/images/products_header.jpg',
                          'products': [   {   'magnified-photo': '/images/panes/165.png',
                                              'photo': '/images/panes/165-small.png',
                                              'productTitle': 'Media Sin Sal',
                                              'quantity': '15',
                                              'reference': '0037',
                                              'weight': '260 g.'},
                                          {   'magnified-photo': '/images/panes/253.png',
                                              'photo': '/images/panes/253-small.png',
                                              'productTitle': 'Pan de Pasas y Nueces 230 g.',
                                              'quantity': '35',
                                              'reference': '0278',
                                              'weight': '230 g.'},
                                          {   'magnified-photo': '/images/panes/234.png',
                                              'photo': '/images/panes/234-small.png',
                                              'productTitle': 'Flauta de Pasas y Nueces',
                                              'quantity': '96',
                                              'reference': '0188',
                                              'weight': '48 g.'},
                                          {   'magnified-photo': '/images/panes/259.png',
                                              'photo': '/images/panes/259-small.png',
                                              'productTitle': 'Baguettina de Pasas y Nueces',
                                              'quantity': '24',
                                              'reference': '0195',
                                              'weight': '110 g.'},
                                          {   'magnified-photo': '/images/panes/278.png',
                                              'photo': '/images/panes/278-small.png',
                                              'productTitle': 'Flauta de Maiz',
                                              'quantity': '96',
                                              'reference': '0181',
                                              'weight': '48 g.'},
                                          {   'magnified-photo': '/images/panes/198.png',
                                              'photo': '/images/panes/198-small.png',
                                              'productTitle': 'Focaccia',
                                              'quantity': '30',
                                              'reference': '0196',
                                              'weight': '110 g.'},
                                          {   'magnified-photo': '/images/panes/211.png',
                                              'photo': '/images/panes/211-small.png',
                                              'productTitle': 'Pan de Pita',
                                              'quantity': '45',
                                              'reference': '0073',
                                              'weight': '55 g.'}]},
    'pan-integral': {   'headerText': 'Pan integral',
                        'photo': '/images/products_header.jpg',
                        'products': [   {   'magnified-photo': '/images/panes/154.png',
                                            'photo': '/images/panes/154-small.png',
                                            'productTitle': 'Medio Bastón Multicereal',
                                            'quantity': '40',
                                            'reference': '0148',
                                            'weight': '120 g.'},
                                        {   'magnified-photo': '/images/panes/180.png',
                                            'photo': '/images/panes/180-small.png',
                                            'productTitle': 'Pan de Centeno y Sesamo',
                                            'quantity': '20',
                                            'reference': '0269',
                                            'weight': '240 g.'},
                                        {   'magnified-photo': '/images/panes/218.png',
                                            'photo': '/images/panes/218-small.png',
                                            'productTitle': 'Baguettina Multicereal',
                                            'quantity': '24',
                                            'reference': '0169',
                                            'weight': '110 g.'},
                                        {   'magnified-photo': '/images/panes/238.png',
                                            'photo': '/images/panes/238-small.png',
                                            'productTitle': 'Flauta Multicereales',
                                            'quantity': '96',
                                            'reference': '0184',
                                            'weight': '48 g.'},
                                        {   'magnified-photo': '/images/panes/254.png',
                                            'photo': '/images/panes/254-small.png',
                                            'productTitle': 'Ritxi Celta Multicereales',
                                            'quantity': '60',
                                            'reference': '0052',
                                            'weight': '100 g.'},
                                        {   'magnified-photo': '/images/panes/307.png',
                                            'photo': '/images/panes/307-small.png',
                                            'productTitle': 'Baston Multicereales',
                                            'quantity': '24',
                                            'reference': '0129',
                                            'weight': '225 g.'}]},
    'pan-rustico': {   'headerText': 'Pan rústico',
                       'photo': '/images/products_header.jpg',
                       'products': [   {   'magnified-photo': '/images/panes/169.png',
                                           'photo': '/images/panes/169-small.png',
                                           'productTitle': 'Rosca Gallega',
                                           'quantity': '6',
                                           'reference': '0099',
                                           'weight': '550 g.'},
                                       {   'magnified-photo': '/images/panes/177.png',
                                           'photo': '/images/panes/177-small.png',
                                           'productTitle': 'Casero',
                                           'quantity': '12',
                                           'reference': '0098',
                                           'weight': '500 g.'},
                                       {   'magnified-photo': '/images/panes/183.png',
                                           'photo': '/images/panes/183-small.png',
                                           'productTitle': 'Baserri',
                                           'quantity': '18',
                                           'reference': '0085',
                                           'weight': '340 g.'},
                                       {   'magnified-photo': '/images/panes/187.png',
                                           'photo': '/images/panes/187-small.png',
                                           'productTitle': 'Txapata Artesana',
                                           'quantity': '16',
                                           'reference': '0111',
                                           'weight': '280 g.'},
                                       {   'magnified-photo': '/images/panes/189.png',
                                           'photo': '/images/panes/189-small.png',
                                           'productTitle': 'Casero Kilo Redondo',
                                           'quantity': '4',
                                           'reference': '0091',
                                           'weight': '1.000 g.'},
                                       {   'magnified-photo': '/images/panes/190.png',
                                           'photo': '/images/panes/190-small.png',
                                           'productTitle': 'Casero Kilo',
                                           'quantity': '4',
                                           'reference': '0096',
                                           'weight': '1.000 g.'},
                                       {   'magnified-photo': '/images/panes/221.png',
                                           'photo': '/images/panes/221-small.png',
                                           'productTitle': 'Berezi',
                                           'quantity': '18',
                                           'reference': '0009',
                                           'weight': '230 g.'},
                                       {   'magnified-photo': '/images/panes/244.png',
                                           'photo': '/images/panes/244-small.png',
                                           'productTitle': 'Casero Menu',
                                           'quantity': '36',
                                           'reference': '0090',
                                           'weight': '100 g.'},
                                       {   'magnified-photo': '/images/panes/301.png',
                                           'photo': '/images/panes/301-small.png',
                                           'productTitle': 'Pan de Leña',
                                           'quantity': '20',
                                           'reference': '0007',
                                           'weight': '350 g.'}]},
    'pan-tradicional': {   'headerText': 'Pan tradicional',
                           'photo': '/images/products_header.jpg',
                           'products': [   {   'magnified-photo': '/images/panes/145.png',
                                               'photo': '/images/panes/145-small.png',
                                               'productTitle': 'Flauta Txapata Plus',
                                               'quantity': '60',
                                               'reference': '0113',
                                               'weight': '50 g.'},
                                           {   'magnified-photo': '/images/panes/166.png',
                                               'photo': '/images/panes/166-small.png',
                                               'productTitle': 'Baguettina Plus',
                                               'quantity': '48',
                                               'reference': '0165',
                                               'weight': '110 g.'},
                                           {   'magnified-photo': '/images/panes/223.png',
                                               'photo': '/images/panes/223-small.png',
                                               'productTitle': 'Baguettina',
                                               'quantity': '48',
                                               'reference': '0168',
                                               'weight': '110 g.'},
                                           {   'magnified-photo': '/images/panes/246.png',
                                               'photo': '/images/panes/246-small.png',
                                               'productTitle': 'Flauta Txapata',
                                               'quantity': '72',
                                               'reference': '0117',
                                               'weight': '35 g.'},
                                           {   'magnified-photo': '/images/panes/248.png',
                                               'photo': '/images/panes/248-small.png',
                                               'productTitle': 'Ritxi Txapata',
                                               'quantity': '25/90',
                                               'reference': '0126',
                                               'weight': '100 g.'},
                                           {   'magnified-photo': '/images/panes/312.png',
                                               'photo': '/images/panes/312-small.png',
                                               'productTitle': 'Barra',
                                               'quantity': '16',
                                               'reference': '0016',
                                               'weight': '350 g.'},
                                           {   'magnified-photo': '/images/panes/313.png',
                                               'photo': '/images/panes/313-small.png',
                                               'productTitle': 'Baguette',
                                               'quantity': '24',
                                               'reference': '0166',
                                               'weight': '230 g.'},
                                           {   'magnified-photo': '/images/panes/261.png',
                                               'photo': '/images/panes/261-small.png',
                                               'productTitle': 'Etxeko',
                                               'quantity': '32',
                                               'reference': '0122',
                                               'weight': '270 g.'},
                                           {   'magnified-photo': '/images/panes/275.png',
                                               'photo': '/images/panes/275-small.png',
                                               'productTitle': 'Flauta Larga',
                                               'quantity': '90',
                                               'reference': '0153',
                                               'weight': '55 g.'},
                                           {   'magnified-photo': '/images/panes/299.png',
                                               'photo': '/images/panes/299-small.png',
                                               'productTitle': 'Italiano Barra',
                                               'quantity': '20',
                                               'reference': '0131',
                                               'weight': '430 g.'},
                                           {   'magnified-photo': '/images/panes/309.png',
                                               'photo': '/images/panes/309-small.png',
                                               'productTitle': 'Bastón',
                                               'quantity': '24',
                                               'reference': '0136',
                                               'weight': '225 g.'},
                                           {   'magnified-photo': '/images/panes/280.png',
                                               'photo': '/images/panes/280-small.png',
                                               'productTitle': 'Flauta',
                                               'quantity': '96',
                                               'reference': '0150',
                                               'weight': '45 g.'},
                                           {   'magnified-photo': '/images/panes/291.png',
                                               'photo': '/images/panes/291-small.png',
                                               'productTitle': 'Ritxi Celta',
                                               'quantity': '60',
                                               'reference': '0049',
                                               'weight': '75 g.'},
                                           {   'magnified-photo': '/images/panes/256.png',
                                               'photo': '/images/panes/256-small.png',
                                               'productTitle': 'Medio Bastón',
                                               'quantity': '40',
                                               'reference': '0138',
                                               'weight': '120 g.'},
                                           {   'magnified-photo': '/images/panes/233.png',
                                               'photo': '/images/panes/233-small.png',
                                               'productTitle': 'Txapata Cuadrada',
                                               'quantity': '60',
                                               'reference': '0115',
                                               'weight': '100 g.'}]},
    'restauracion-bocata': {   'headerText': 'Bocata',
                               'photo': '/images/products_header.jpg',
                               'products': [   {   'magnified-photo': '/images/panes/158.png',
                                                   'photo': '/images/panes/158-small.png',
                                                   'productTitle': 'Bocatta',
                                                   'quantity': '40',
                                                   'reference': '0143',
                                                   'weight': '150 g.'},
                                               {   'magnified-photo': '/images/panes/283.png',
                                                   'photo': '/images/panes/283-small.png',
                                                   'productTitle': 'Perrito',
                                                   'quantity': '48',
                                                   'reference': '0190',
                                                   'weight': '100 g.'},
                                               {   'magnified-photo': '/images/panes/226.png',
                                                   'photo': '/images/panes/226-small.png',
                                                   'productTitle': 'Flauta Bocata',
                                                   'quantity': '60',
                                                   'reference': '0151',
                                                   'weight': '130 g.'}]},
    'restauracion-burger': {   'headerText': 'Burger',
                               'photo': '/images/products_header.jpg',
                               'products': [   {   'magnified-photo': '/images/panes/137.png',
                                                   'photo': '/images/panes/137-small.png',
                                                   'productTitle': 'Mini Burger',
                                                   'quantity': '100',
                                                   'reference': '0145',
                                                   'weight': '30 g.'},
                                               {   'magnified-photo': '/images/panes/128.png',
                                                   'photo': '/images/panes/128-small.png',
                                                   'productTitle': 'Txapata Burger',
                                                   'quantity': '45',
                                                   'reference': '0128',
                                                   'weight': '150 g.'},
                                               {   'magnified-photo': '/images/panes/201.png',
                                                   'photo': '/images/panes/201-small.png',
                                                   'productTitle': 'Burger Plus',
                                                   'quantity': '48',
                                                   'reference': '0154',
                                                   'weight': '150 g.'},
                                               {   'magnified-photo': '/images/panes/202.png',
                                                   'photo': '/images/panes/202-small.png',
                                                   'productTitle': 'Mini Burger Integral Sesamo',
                                                   'quantity': '100',
                                                   'reference': '0140',
                                                   'weight': '35 g.'},
                                               {   'magnified-photo': '/images/panes/205.png',
                                                   'photo': '/images/panes/205-small.png',
                                                   'productTitle': 'Mini Burger Semillas',
                                                   'quantity': '100',
                                                   'reference': '0146',
                                                   'weight': '30 g.'},
                                               {   'magnified-photo': '/images/panes/207.png',
                                                   'photo': '/images/panes/207-small.png',
                                                   'productTitle': 'Mini Burger Amapola',
                                                   'quantity': '100',
                                                   'reference': '0147',
                                                   'weight': '30 g.'},
                                               {   'magnified-photo': '/images/panes/216.png',
                                                   'photo': '/images/panes/216-small.png',
                                                   'productTitle': 'Talo Burguer',
                                                   'quantity': '27',
                                                   'reference': '0197',
                                                   'weight': '140 g.'}]},
    'restauracion-pintxo': {   'headerText': 'Pintxo',
                               'photo': '/images/products_header.jpg',
                               'products': [   {   'magnified-photo': '/images/panes/152.png',
                                                   'photo': '/images/panes/152-small.png',
                                                   'productTitle': 'Ritxi Pequeño (Pulga)',
                                                   'quantity': '150',
                                                   'reference': '0051',
                                                   'weight': '25 g.'},
                                               {   'magnified-photo': '/images/panes/265.png',
                                                   'photo': '/images/panes/265-small.png',
                                                   'productTitle': 'Ritxi Mini',
                                                   'quantity': '120',
                                                   'reference': '0053',
                                                   'weight': '30 g.'},
                                               {   'magnified-photo': '/images/panes/267.png',
                                                   'photo': '/images/panes/267-small.png',
                                                   'productTitle': 'Txapata Pintxo',
                                                   'quantity': '96',
                                                   'reference': '0118',
                                                   'weight': '30 g.'},
                                               {   'magnified-photo': '/images/panes/272.png',
                                                   'photo': '/images/panes/272-small.png',
                                                   'productTitle': 'Celta Pintxo Plus',
                                                   'quantity': '90',
                                                   'reference': '0055',
                                                   'weight': '40 g.'},
                                               {   'magnified-photo': '/images/panes/286.png',
                                                   'photo': '/images/panes/286-small.png',
                                                   'productTitle': 'Celta Pintxo',
                                                   'quantity': '108',
                                                   'reference': '0058',
                                                   'weight': '25 g.'},
                                               {   'magnified-photo': '/images/panes/288.png',
                                                   'photo': '/images/panes/288-small.png',
                                                   'productTitle': 'Celta Pintxo Multicereal',
                                                   'quantity': '108',
                                                   'reference': '0064',
                                                   'weight': '35 g.'}]}}
var CategoryView = backbone.View.extend({
	initialize: function(initData){
		this.render(initData.category);
	},
	template: require("../../views/category.hbs"),
	render: function(category){
		var categoryData = data[category];
        this.$el.html(this.template({category: categoryData.headerText, products: categoryData.products}));
		var headerView = new HeaderView({el: $(".header")});
		var contentHeader = new ContentHeaderView({el: $("#content-header"), headerText: categoryData.headerText, photo: categoryData.photo });
        var footer_view = new FooterView({el: $("footer")});
        $('[data-toggle="magnify"]').each(function () {
            var $mag = $(this);
            $mag.magnify()
        });
	}
});

module.exports = CategoryView;
